### ISSUE TITLE
Python implementation- no visualization.

### ISSUE THREAD

**Issue by moonsh** [francescofarina/HeadedSocialForceModel#3]
Hi, First, thank you for sharing your code (Python).

I followed your guide and it works but there is no visualization.

It only shows the time measurements. 

How can I get visualization for the simulation as you did in the paper?

**Comment by francescofarina** [comment]
Hi,
The visualizzaton is implemented only in the matlab code. You can take a
look at it to implement the python contepart of you need it.

Il giorno Lun 4 Feb 2019, 17:27 Seonghyeon Moon <notifications@github.com>
ha scritto:

**Comment by moonsh** [comment]
@francescofarina Thank you
